swagger: '2.0'
info:
  title: Test API
  description: Test API
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
paths:
  /categories:
    get:
      description: Return a list of categories.
      responses:
        '200':
          description: Returned a list of categories.
        '400':
          description: Bad request.
        '404':
          description: Path not found.
        '500':
          description: Internal server error.
    post:
      description: Create a category.
      responses:
        '200':
          description: Created a new category.
        '400':
          description: Bad request.
        '404':
          description: Path not found.
        '500':
          description: Internal server error.
  '/categories/:id':
    put:
      description: Update a category.
      responses:
        '200':
          description: Updated a new category.
        '400':
          description: Bad request.
        '404':
          description: Path not found.
        '500':
          description: Internal server error.
    delete:
      description: Delete a category
      responses:
        '200':
          description: Deleted a new category.
        '400':
          description: Bad request.
        '404':
          description: Path not found.
        '500':
          description: Internal server error.
  /products:
    get:
      description: Return a list of products.
      responses:
        '200':
          description: Returned a list of products.
        '400':
          description: Bad request.
        '404':
          description: Path not found.
        '500':
          description: Internal server error.
    post:
      description: Create a products.
      responses:
        '200':
          description: Created a new products.
        '400':
          description: Bad request.
        '404':
          description: Path not found.
        '500':
          description: Internal server error.
  '/products/:id':
    put:
      description: Update a products.
      responses:
        '200':
          description: Updated a new products.
        '400':
          description: Bad request.
        '404':
          description: Path not found.
        '500':
          description: Internal server error.
    delete:
      description: Delete a products
      responses:
        '200':
          description: Deleted a new products.
        '400':
          description: Bad request.
        '404':
          description: Path not found.
        '500':
          description: Internal server error.
